### ISSUE TITLE
BGP wedgies lab FRR as-path access list config error

### ISSUE THREAD

**Issue by chonty** [bgplab/bgplab#16]
netlab version: 1.8.4
FRR version: 7.5

defaults.yml:
```
device: eos         # Change to your preferred network device
provider: clab          # Change to virtualbox or libvirt if needed

groups:
  external:
    device: frr                                   # Change to your preferred external router

devices.eos.clab.image: "ceos:4.32.1F"
devices.eos.clab.node.env.CLAB_MGMT_VRF: management   # Add management VRF to cEOS. Not needed after 1.6.4
devices.frr.features.ospf.unnumbered: true            # OSPF unnumbered works on FRR. Not needed after 1.7.0
devices.frr.clab.image: quay.io/frrouting/frr:7.5.0   # The last image that handles loopbacks correctly
```
```
p2# sh ver
FRRouting 7.5_git (p2).
Copyright 1996-2005 Kunihiro Ishiguro, et al.
configured with:
    '--prefix=/usr' '--sbindir=/usr/lib/frr' '--sysconfdir=/etc/frr' '--libdir=/usr/lib' '--localstatedir=/var/run/frr' '--enable-systemd=no' '--enable-rpki' '--enable-vtysh' '--enable-multipath=64' '--enable-vty-group=frrvty' '--enable-user=frr' '--enable-group=frr' 'CC=gcc' 'CXX=g++'
```

File: https://github.com/bgplab/bgplab/blob/master/policy/e-wedgies/config/p2.cfg
or
https://github.com/bgplab/bgplab/blob/master/policy/e-wedgies/extra-config/p2.frr.j2

Error:
```
TASK [run vtysh to import extra-config config from /home/netlab/bgplab/policy/e-wedgies/extra-config/p2.frr.j2] ***************************************************************************
fatal: [p2]: FAILED! => changed=true 
  cmd:
  - vtysh
  - -f
  - /tmp/config.sh
  delta: '0:00:00.074259'
  end: '2024-07-01 09:22:18.029368'
  msg: non-zero return code
  rc: 2
  start: '2024-07-01 09:22:17.955109'
  stderr: |-
    line 3: % Unknown command[4]: bgp as-path access-list transit-path seq 10 deny ^([0-9]+)(_\1)*$
    line 4: % Unknown command[4]: bgp as-path access-list transit-path seq 20 permit .*
  stderr_lines: <omitted>
  stdout: ''
  stdout_lines: <omitted>

PLAY RECAP ********************************************************************************************************************************************************************************
c1                         : ok=17   changed=2    unreachable=0    failed=0    skipped=2    rescued=0    ignored=0   
p1                         : ok=21   changed=5    unreachable=0    failed=0    skipped=6    rescued=0    ignored=0   
p2                         : ok=28   changed=6    unreachable=0    failed=1    skipped=10   rescued=0    ignored=0   
u1                         : ok=21   changed=5    unreachable=0    failed=0    skipped=6    rescued=0    ignored=0   
u2                         : ok=21   changed=5    unreachable=0    failed=0    skipped=6    rescued=0    ignored=0   
```

`as-path access-list transit-path seq xxx` is not valid on FRR 7.5 but it does work on Cumulus and the more recent FRR version I tested, 9.1.0.
Omitting the sequence numbering is required for 7.5:
```
bgp as-path access-list transit-path deny ^([0-9]+)(_\1)*$
bgp as-path access-list transit-path permit .*
```
